# General programs in here
{
  config,
  pkgs,
  inputs,
  ...
}: {
  environment.systemPackages = with pkgs; [
    firefox
    brave
    anki-bin
    discord
    inputs.zen-browser.packages."${pkgs.system}".twilight
    thunderbird
    ffmpeg
    mpv
    wget
    unar
    unzip
    htop
    btop
    radeontop
    nvtopPackages.amd
    powertop
    fastfetch
    kitty
    zathura
    libreoffice-qt6-fresh
    hunspell
    hunspellDicts.en_GB-ize
    hunspellDicts.en_GB-large
    hunspellDicts.en_US-large
    blueman
    bambu-studio
    krita
    prismlauncher
    pandoc
  ];
}
